/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mih14' at '25/02/18 13:28' with Gradle 2.14.1
 *
 * @author mih14, @date 25/02/18 13:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
